"""empty message

Revision ID: 3af231778b95
Revises: 7efca049572b
Create Date: 2025-03-20 18:36:33.110462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af231778b95'
down_revision = '7efca049572b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historie', schema=None) as batch_op:
        batch_op.alter_column('bearbeiter_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historie', schema=None) as batch_op:
        batch_op.alter_column('bearbeiter_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
