"""Oberkategorie weg, Unterkategorie wird zu Kategorie

Revision ID: 66c8cdc18610
Revises: 7992eeff1dcf
Create Date: 2025-03-16 16:44:45.173156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66c8cdc18610'
down_revision = '7992eeff1dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    kategorie_enum = sa.Enum('TIPPFEHLER', 'INHALTLICHER_FEHLER', 'FORMATIERUNGSFEHLER', 'ERWEITERUNG', 'STRUKTURVERBESSERUNG', name='kategorie')
    kategorie_enum.create(op.get_bind())
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategorie', kategorie_enum, nullable=False))
        batch_op.drop_column('kategorie_haupt')
        batch_op.drop_column('kategorie_unter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategorie_unter', postgresql.ENUM('TIPPFEHLER', 'INHALTLICHER_FEHLER', 'FORMATIERUNGSFEHLER', 'ERWEITERUNG', 'STRUKTURVERBESSERUNG', name='kategorieunter'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kategorie_haupt', postgresql.ENUM('FEHLER', 'VERBESSERUNGSVORSCHLAG', name='kategoriehaupt'), autoincrement=False, nullable=False))
        batch_op.drop_column('kategorie')

    kategorie_enum = sa.Enum('TIPPFEHLER', 'INHALTLICHER_FEHLER', 'FORMATIERUNGSFEHLER', 'ERWEITERUNG', 'STRUKTURVERBESSERUNG', name='kategorie')
    kategorie_enum.drop(op.get_bind())

    # ### end Alembic commands ###
